#!/bin/bash
#
# To generate files with correct permissions use: sudo -u www-data ./datapaths input.txt
#
# @author Robert Boloc <robertboloc@gmail.com>
# @copyright (c) 2013, Robert Boloc (http://robertboloc.eu)
# @license http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
#

cat $1 | while read f;
do
  if [[ "$f" = */* ]]; then
    mkdir -p "${f%/*}";
  fi;

  echo 'Generating file '$f;
  touch "$f";
done
