#!/bin/bash
#
# Clean up files generated during the process
#
# @author Robert Boloc <robertboloc@gmail.com>
# @copyright (c) 2013, Robert Boloc (http://robertboloc.eu)
# @license http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
#

echo $NOW'Starting cleanup...';

# Remove the original file

if [ -f $BASEPATH''db/backup.sql ]
then
  echo $NOW'Removing file'$BASEPATH''db/backup.sql;
  rm $BASEPATH''db/backup.sql;
fi