#!/bin/bash
#
# Removes excluded tables dumps from the filesystem
#
# @author Robert Boloc <robertboloc@gmail.com>
# @copyright (c) 2013, Robert Boloc (http://robertboloc.eu)
# @license http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
#

for excluded in $EXCLUDE
do
    rm $BASEPATH'db/sqls/'$excluded'.sql'
done
